version: "3"

services:
  db:
    image: "postgres:16"
    restart: "unless-stopped"
    ports:
      - "5555:5432"
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    env_file:
      - .env
